### ISSUE TITLE
Fix exception for a specific travel request

### ISSUE THREAD

**Issue by tuetschek** [UFAL-DSG/alex#171]
CRWS/Idos web service will fail on request given by this prompt:

    z náměstí republiky do neratovice železniční stanice

The error message looks as follows:

    2015-07-04--14-17-15.200130-CEST  DM-7       : INFO       
        ALEX: Neratovice, železniční stanice -- Neratovice, Náměstí Republiky -- Neratovice

    2015-07-04--14-17-15.206469-CEST  DM-7       : INFO       
        IDOS: Neratovice,žel.st. -- Praha,  Neratovice,,Nám.Republiky -- Neratovice

    2015-07-04--14-17-15.233078-CEST  DM-7       : INFO       
        CRWS Request for connection:
        
        FROM: (ArrayOfGlobalListItemInfo){
           GlobalListItemInfo[] = 
              (GlobalListItemInfo){
                 _iItem = 1351
                 _sName = "Neratovice,žel.st."
                 _iListID = 301003
              },
         }
        
        TO: (ArrayOfGlobalListItemInfo){
           GlobalListItemInfo[] = 
              (GlobalListItemInfo){
                 _iItem = 14
                 _sName = "Neratovice,,Nám.Republiky"
                 _iListID = 248003
              },
         }
        
        TIME_STAMP: 2015-07-04 17:30:00
        IS_DEPARTURE: True
        

    2015-07-04--14-17-15.258886-CEST  DM-7       : EXCEPTION  
        Uncaught exception in the DM process.
        Traceback (most recent call last):
          File "/mnt/h/jurcicek/github/UFAL-DSG-alex-prd/alex/components/hub/dm.py", line 274, in run
            self.read_slu_hypotheses_write_dialogue_act()
          File "/mnt/h/jurcicek/github/UFAL-DSG-alex-prd/alex/components/hub/dm.py", line 223, in read_slu_hypotheses_write_dialogue_act
            da = self.dm.da_out()
          File "/mnt/h/jurcicek/github/UFAL-DSG-alex-prd/alex/components/dm/base.py", line 197, in da_out
            self.last_system_dialogue_act = self.policy.get_da(self.dialogue_state)
          File "/mnt/h/jurcicek/github/UFAL-DSG-alex-prd/alex/applications/PublicTransportInfoCS/hdc_policy.py", line 301, in get_da
            accepted_slots, changed_slots, has_state_changed)
          File "/mnt/h/jurcicek/github/UFAL-DSG-alex-prd/alex/applications/PublicTransportInfoCS/hdc_policy.py", line 349, in get_connection_res_da
            res_da.extend(self.get_directions(ds, check_conflict=True))
          File "/mnt/h/jurcicek/github/UFAL-DSG-alex-prd/alex/applications/PublicTransportInfoCS/hdc_policy.py", line 1143, in get_directions
            arrival_time=arrival_ts)
          File "/mnt/h/jurcicek/github/UFAL-DSG-alex-prd/alex/utils/cache.py", line 66, in wrapper
            result = user_function(*args, **kwds)
          File "/mnt/h/jurcicek/github/UFAL-DSG-alex-prd/alex/applications/PublicTransportInfoCS/directions.py", line 664, in get_directions
            0)
          File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 542, in __call__
            return client.invoke(args, kwargs)
          File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 602, in invoke
            result = self.send(soapenv)
          File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 649, in send
            result = self.failed(binding, e)
          File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 702, in failed
            r, p = binding.get_fault(reply)
          File "/usr/local/lib/python2.7/dist-packages/suds/bindings/binding.py", line 265, in get_fault
            raise WebFault(p, faultroot)
        WebFault: Server raised fault: 'The server was unable to process the request due to an internal error.  For more information about the error, either turn on IncludeExceptionDetailInFaults (either from ServiceBehaviorAttribute or from the <serviceDebug> configuration behavior) on the server in order to send the exception information back to the client, or turn on tracing as per the Microsoft .NET Framework SDK documentation and inspect the server trace logs.'

The request looks legitimate and I have not yet found a way to turn the debugging on in SUDS.

**Comment by tuetschek** [comment]
This was actually a more general issue (CRWS changed their API). Fixed in #172 .
