### ISSUE TITLE
Travis builds failing due to SciPy import error

### ISSUE THREAD

**Issue by tuetschek** [UFAL-DSG/alex#182]
The Travis build has been failing with this error:

    0.16s$ python -c 'import alex.applications.vhub'
    Vendor:  Continuum Analytics, Inc.
    Package: mkl
    Message: trial mode expires in 30 days
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "alex/applications/vhub.py", line 12, in <module>
        from alex.applications.voicehub import VoiceHub
      File "alex/applications/voicehub.py", line 12, in <module>
        from alex.components.hub.vad import VAD
      File "alex/components/hub/vad.py", line 16, in <module>
        import alex.components.vad.gmm as GVAD
      File "alex/components/vad/gmm.py", line 6, in <module>
        from scipy.misc import logsumexp
      File "/home/travis/miniconda/envs/pyenv/lib/python2.7/site-packages/scipy/misc/__init__.py", line 49, in <module>
        from scipy.special import comb, factorial, factorial2, factorialk
      File "/home/travis/miniconda/envs/pyenv/lib/python2.7/site-packages/scipy/special/__init__.py", line 601, in <module>
        from ._ufuncs import *

    ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory
    The command "python -c 'import alex.applications.vhub'" exited with 1.

Do you know how to fix this?

**Comment by ticcky** [comment]
Seems like similar problem:
https://github.com/MDAnalysis/GridDataFormats/commit/41b8d96f1514757a9e43c97089c2b89d87ccb246

Just trying out whether it helps for us too.
